### ISSUE TITLE
正解と不正解に対する音とエフェクト

### ISSUE THREAD

**Issue by mirrei-y** [1STEP621/languessr#11]
SE作成能力　少し
エフェクト作成能力　少し
時間　なし
やる気　なし

………
みれいエフェクトつくれないよおおおおおおおおおおおおおおおおおおおおおおおおおお

**Comment by 1STEP621** [comment]
音Done

**Comment by 1STEP621** [comment]
Done in ddde9c42f51e5a83715b24e982501f59998216c9
