### ISSUE TITLE
TitleView での難易度調整

### ISSUE THREAD

**Issue by mirrei-y** [1STEP621/languessr#13]
時間とか問題数とか

**Comment by 1STEP621** [comment]
## Hard
ヒントなし
最大減点ポイントなし
時間経過で不正解あり
## Normal
ヒントあり
最大減点ポイントなし
時間経過で不正解なし
## Easy
ヒントあり
最大減点ポイントあり
時間経過で不正解なし

**Comment by 1STEP621** [comment]
デザインとコントローラー対応お願いします

**Comment by 1STEP621** [comment]
Done in 7434a3d7ff925a750f87aeb88fe6694bccfeb7be
